### ISSUE TITLE
Create ability in renderer method to generate Markdown

### ISSUE THREAD

**Issue by drewry** [opendnd/personae#1]
Should have an easy way to generate Markdown from a `person` so it can be easily added to compendia.

**Comment by drewry** [comment]
@naltun if you want to take a crack at this let me know. I’d suggest a new static method above here https://github.com/opendnd/personae/blob/bb0f609838f8ba622d7f741322a0eb57afdc6f5d/lib/renderer.js#L4

Similar content as the output but instead of formatting it for console output we would format it in markdown. Something like:

```markdown
# Character Name

## Introduction
> My name is blah blah, etc

## Abiltities
- INT: blah
- CHA: blah
```

**Comment by naltun** [comment]
I'll take a crack at it, definitely. Any expected or required timeframe?

**Comment by drewry** [comment]
Nooe, anytime you can get to it would be great. Eventually I’d like all the tools to have a markdown output option so some of the others may take more time. So this one would be good to gauge how long the others may take.

**Comment by naltun** [comment]
Okay, so I'll get to it one of these afternoons this week (maybe even today, or tomorrow); whichever afternoon I start on, I'll leave a message here to let you know when I started. That way we can gauge more efficiently.

**Comment by naltun** [comment]
Commit 32e3b18 applies to this issue.

**Comment by naltun** [comment]
Commit dd14742 pushed to `feature/markdown`. The generated Markdown file spits out random characters, a la reading from binary files.

**Comment by drewry** [comment]
@naltun thanks for the help, going to merge this PR https://github.com/opendnd/personae/pull/2
