### ISSUE TITLE
The selected alignment was not the one in the introduction

### ISSUE THREAD

**Issue by naltun** [opendnd/personae#8]
I am using `opendnd` version `0.4.1`. I `dnd name gen`'d and created my character. I selected 'Neutral Good' and the introduction says `I am a male Tiefling Bard and my alignment is True Neutral.`

The only thing I did was type in `Neutral good` without caps in 'good.' I'm going to try and reproduce this.

**Comment by drewry** [comment]
I see what's going on, if you don't type it exactly as written it will not find it. We should add a check where it lowercases everything to prevent that issue.
