### ISSUE TITLE
'My' is capital in introduction in the middle of the sentence

### ISSUE THREAD

**Issue by naltun** [opendnd/personae#9]
I am using `opendnd` version `0.4.1`. After `dnd name gen` I got this sentence:
`I'd say my biggest flaw is that My hatred of my enemies is blind and unreasoning.`

Note that the 'my' is capital.

**Comment by naltun** [comment]
Commit 0c5760b references this issue.

Currently I am getting `TypeError: Cannot read property 'toLowerCase' of undefined` when running personae. `flaw` is undefined then, correct? Does `flaw` have to be a constant?

**Comment by drewry** [comment]
Here's what I was talking about here 8fa0480762b53cc2afdc442d639d0e196f7e8b0f

Also this will get fixed in https://github.com/opendnd/personae/pull/10
